Add Bitski injected wallet
wagmi-dev/wagmi pull request #1215
Opened 2022-11-01 15:55 UTC by pzuraq

## Description

Add support for the [Bitski browser extension](https://chrome.google.com/webstore/detail/bitski/feejiigddaafeojfddjjlmfkabimkell) wallet, which allows users to use the [Bitski](https://bitski.com/) wallet with Dapps that only support injected/browser extension wallets.

## Additional Information

- [x] I read the [contributing docs](/wagmi-dev/wagmi/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

Your ENS/address: 0xb9b7d3d6317d987548919641c8bf1f539da275fc

2022-11-01 17:59 UTC, pzuraq commented
It's not entirely clear if it makes sense to add a Bitski connector here, but in testing out RainbowKit with these changes we're seeing that when multiple wallets are injected at the same time (e.g. MetaMask, Coinbase, and Bitski), clicking the MetaMask button works but clicking the Bitski button does not. This is because the MetaMask connector has some extra logic to search `window.ethereum.providers` if it exists.

We'd be happy to add this logic along with an identification function to the `InjectedConnector` class directly. Alternatively, we could subclass `InjectedConnector` and add this functionality directly in RainbowKit, if that's the preferred way to add a wallet.

2022-11-02 19:05 UTC, tmm requested changes
We can discuss adding this to the core in the future, but please remove the Bitski-specific Connector code for now (e.g. `packages/src/core/connectors/bitski`). Adding new built-in connectors adds more surface area for the core team (me and @jxom) to manage.

In the meantime, feel free to [share this code](https://github.com/tmm/wagmi/discussions/new?category=show-and-tell) in the GitHub Discussion area or package it up as a standalone package.

2022-11-02 19:05 UTC, tmm commented on .changeset/khaki-jokes-move.md
> +Add support for the Bitski browser extension
```suggestion
Added Bitski wallet support to `InjectedConnector`
```

2022-11-02 19:05 UTC, tmm commented on .changeset/khaki-jokes-move.md
> +'@wagmi/core': patch
This changeset should also include `wagmi`

```suggestion
'@wagmi/core': patch
'wagmi': patch
```

2022-11-09 02:17 UTC, tmm commented
@pzuraq going to close this for now. feel free to reopen when you make changes.

2022-11-09 02:17 UTC, closed without merging

2022-11-09 03:06 UTC, pzuraq commented
Sounds good! Been a busy week but will get it updated soon